### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by kirtan0000** [abstractmark/javascript#1]
How do I run this?

**Comment by kimlimjustin** [comment]
Hello, Kirtan. note that `abstractmark` is still in development progress. However, if you want to run this, please follow the following steps:

- Clone this repository by typing `git clone https://github.com/abstractmark/javascript.git abstractmark`
- Get into the repository by typing `cd abstractmark`
- You can run abstractmark by both require it inside a javascript file or as CLI (command line). However, I strongly suggest running through Command-Line if you want to join our development.
- To install abstractmark as CLI, please install it globally using the `npm` package manager by typing `npm i -g`.

  Nb: if you using Linux and it keep shows that the abstractmark command is not recognized, type the following command `sudo npm install -g --force`

- Type `abstractmark <abstractmark file>` to run it. 

More information about the installation guide and others will be written in the README file of this repository once it is stable and there will a documentation site about this.

Once again, we appreciate all contributions to abstractmark by even sharing it, staring it or make a contribution.

Best regards,
Justin

**Comment by kirtan0000** [comment]
Thanks!
